ffmpeg: update pkg-config patch

diff --git a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
--- a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
+++ b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
@@ -1,18 +1,18 @@
-From 9e9b9518ca2c74fe10bca198b635833477ddba10 Mon Sep 17 00:00:00 2001
+From eb2ca698516d6cb66e18943c3ed8cbfb8f84dc63 Mon Sep 17 00:00:00 2001
 From: Martin Herkt <lachs0r@srsfckn.biz>
 Date: Fri, 31 Jan 2014 11:33:27 +0100
-Subject: [PATCH] Fix pkg-config for static builds and use it for more external
- libs
+Subject: [PATCH] Fix pkg-config for static builds and use it for more
+ external libs
 
 ---
- configure | 27 ++++++++++++---------------
- 1 file changed, 12 insertions(+), 15 deletions(-)
+ configure |   25 ++++++++++++-------------
+ 1 files changed, 12 insertions(+), 13 deletions(-)
 
 diff --git a/configure b/configure
-index 8b88daf..bf324e2 100755
+index 106852e..4cebc4e 100755
 --- a/configure
 +++ b/configure
-@@ -2813,6 +2813,8 @@ set_default host_cc
+@@ -2823,6 +2823,8 @@ set_default host_cc
  if ! $pkg_config --version >/dev/null 2>&1; then
      warn "$pkg_config not found, library detection may fail."
      pkg_config=false
@@ -21,7 +21,7 @@ index 8b88daf..bf324e2 100755
  fi
  
  exesuf() {
-@@ -4429,28 +4431,26 @@ enabled ladspa            && { check_header ladspa.h || die "ERROR: ladspa.h hea
+@@ -4442,26 +4444,26 @@ enabled ladspa            && { check_header ladspa.h || die "ERROR: ladspa.h hea
  enabled libiec61883       && require libiec61883 libiec61883/iec61883.h iec61883_cmp_connect -lraw1394 -lavc1394 -lrom1394 -liec61883
  enabled libaacplus        && require "libaacplus >= 2.0.0" aacplus.h aacplusEncOpen -laacplus
  enabled libass            && require_pkg_config libass ass/ass.h ass_library_init
@@ -32,9 +32,7 @@ index 8b88daf..bf324e2 100755
                                 die "ERROR: libcelt must be installed and version must be >= 0.11.0."; }
  enabled libcaca           && require_pkg_config caca caca.h caca_create_canvas
  enabled libfaac           && require2 libfaac "stdint.h faac.h" faacEncGetVersion -lfaac
--enabled libfdk_aac        && require libfdk_aac fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac &&
--                             { check_cpp_condition fdk-aac/aacenc_lib.h "AACENCODER_LIB_VL0 >= 3 && AACENCODER_LIB_VL1 >= 4 && AACENCODER_LIB_VL2 >= 12" ||
--                               die "ERROR: libfdk_aac must be installed and version must be >= 3.4.12."; }
+-enabled libfdk_aac        && require libfdk_aac fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac
 +enabled libfdk_aac        && require_pkg_config fdk-aac fdk-aac/aacenc_lib.h aacEncOpen
  flite_libs="-lflite_cmu_time_awb -lflite_cmu_us_awb -lflite_cmu_us_kal -lflite_cmu_us_kal16 -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmulex -lflite"
  enabled libflite          && require2 libflite "flite/flite.h" flite_init $flite_libs
@@ -56,7 +54,7 @@ index 8b88daf..bf324e2 100755
  enabled libopencv         && require_pkg_config opencv opencv/cxcore.h cvCreateImageHeader
  enabled libopenjpeg       && { check_lib openjpeg-1.5/openjpeg.h opj_version -lopenjpeg ||
                                 check_lib openjpeg.h opj_version -lopenjpeg ||
-@@ -4463,11 +4463,11 @@ enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/sc
+@@ -4474,11 +4476,11 @@ enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/sc
  enabled libshine          && require_pkg_config shine shine/layer3.h shine_encode_buffer
  enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr
  enabled libssh            && require_pkg_config libssh libssh/sftp.h sftp_init
@@ -70,7 +68,7 @@ index 8b88daf..bf324e2 100755
  enabled libtwolame        && require libtwolame twolame.h twolame_init -ltwolame &&
                               { check_lib twolame.h twolame_encode_buffer_float32_interleaved -ltwolame ||
                                 die "ERROR: libtwolame must be installed and version must be >= 0.3.10"; }
-@@ -4476,7 +4476,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
+@@ -4487,7 +4489,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
  enabled libvidstab        && require_pkg_config "vidstab >= 0.98" vid.stab/libvidstab.h vsMotionDetectInit
  enabled libvo_aacenc      && require libvo_aacenc vo-aacenc/voAAC.h voGetAACEncAPI -lvo-aacenc
  enabled libvo_amrwbenc    && require libvo_amrwbenc vo-amrwbenc/enc_if.h E_IF_init -lvo-amrwbenc
@@ -79,7 +77,7 @@ index 8b88daf..bf324e2 100755
  enabled libvpx            && {
      enabled libvpx_vp8_decoder && { check_lib2 "vpx/vpx_decoder.h vpx/vp8dx.h" vpx_codec_dec_init_ver -lvpx ||
                                      die "ERROR: libvpx decoder version must be >=0.9.1"; }
-@@ -4512,10 +4512,7 @@ enabled opengl            && { check_lib GL/glx.h glXGetProcAddress "-lGL" ||
+@@ -4523,10 +4525,7 @@ enabled opengl            && { check_lib GL/glx.h glXGetProcAddress "-lGL" ||
                                 check_lib2 ES2/gl.h glGetError "-isysroot=${sysroot} -Wl,-framework,OpenGLES" ||
                                 die "ERROR: opengl not found."
                               }
@@ -92,5 +90,5 @@ index 8b88daf..bf324e2 100755
  if enabled gnutls; then
      { check_lib nettle/bignum.h nettle_mpz_get_str_256 -lnettle -lhogweed -lgmp && enable nettle; } ||
 -- 
-1.8.5
+1.7.9
 
