ffmpeg: update pkg-config patch

diff --git a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
--- a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
+++ b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
@@ -1,18 +1,18 @@
-From 0aeb8e74e7fd19a8988d3ea483633bbd3587b33f Mon Sep 17 00:00:00 2001
+From 701aa4777c8f2ad8ce309511f33b47bddab4327b Mon Sep 17 00:00:00 2001
 From: Martin Herkt <lachs0r@srsfckn.biz>
-Date: Tue, 21 Jan 2014 11:58:32 +0100
+Date: Sun, 26 Jan 2014 05:54:57 +0100
 Subject: [PATCH] Fix pkg-config for static builds and use it for more external
  libs
 
 ---
- configure | 25 ++++++++++++-------------
- 1 file changed, 12 insertions(+), 13 deletions(-)
+ configure | 27 ++++++++++++---------------
+ 1 file changed, 12 insertions(+), 15 deletions(-)
 
 diff --git a/configure b/configure
-index 7b4cfc5..c98ed75 100755
+index 1a91e02..a913615 100755
 --- a/configure
 +++ b/configure
-@@ -2805,6 +2805,8 @@ set_default host_cc
+@@ -2804,6 +2804,8 @@ set_default host_cc
  if ! $pkg_config --version >/dev/null 2>&1; then
      warn "$pkg_config not found, library detection may fail."
      pkg_config=false
@@ -21,7 +21,7 @@ index 7b4cfc5..c98ed75 100755
  fi
  
  exesuf() {
-@@ -4419,26 +4421,26 @@ enabled ladspa            && { check_header ladspa.h || die "ERROR: ladspa.h hea
+@@ -4420,28 +4422,26 @@ enabled ladspa            && { check_header ladspa.h || die "ERROR: ladspa.h hea
  enabled libiec61883       && require libiec61883 libiec61883/iec61883.h iec61883_cmp_connect -lraw1394 -lavc1394 -lrom1394 -liec61883
  enabled libaacplus        && require "libaacplus >= 2.0.0" aacplus.h aacplusEncOpen -laacplus
  enabled libass            && require_pkg_config libass ass/ass.h ass_library_init
@@ -32,7 +32,9 @@ index 7b4cfc5..c98ed75 100755
                                 die "ERROR: libcelt must be installed and version must be >= 0.11.0."; }
  enabled libcaca           && require_pkg_config caca caca.h caca_create_canvas
  enabled libfaac           && require2 libfaac "stdint.h faac.h" faacEncGetVersion -lfaac
--enabled libfdk_aac        && require libfdk_aac fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac
+-enabled libfdk_aac        && require libfdk_aac fdk-aac/aacenc_lib.h aacEncOpen -lfdk-aac &&
+-                             { check_cpp_condition fdk-aac/aacenc_lib.h "AACENCODER_LIB_VL0 >= 3 && AACENCODER_LIB_VL1 >= 4 && AACENCODER_LIB_VL2 >= 12" ||
+-                               die "ERROR: libfdk_aac must be installed and version must be >= 3.4.12."; }
 +enabled libfdk_aac        && require_pkg_config fdk-aac fdk-aac/aacenc_lib.h aacEncOpen
  flite_libs="-lflite_cmu_time_awb -lflite_cmu_us_awb -lflite_cmu_us_kal -lflite_cmu_us_kal16 -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmulex -lflite"
  enabled libflite          && require2 libflite "flite/flite.h" flite_init $flite_libs
@@ -54,7 +56,7 @@ index 7b4cfc5..c98ed75 100755
  enabled libopencv         && require_pkg_config opencv opencv/cxcore.h cvCreateImageHeader
  enabled libopenjpeg       && { check_lib openjpeg-1.5/openjpeg.h opj_version -lopenjpeg ||
                                 check_lib openjpeg.h opj_version -lopenjpeg ||
-@@ -4451,11 +4453,11 @@ enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/sc
+@@ -4454,11 +4454,11 @@ enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/sc
  enabled libshine          && require_pkg_config shine shine/layer3.h shine_encode_buffer
  enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr
  enabled libssh            && require_pkg_config libssh libssh/sftp.h sftp_init
@@ -68,7 +70,7 @@ index 7b4cfc5..c98ed75 100755
  enabled libtwolame        && require libtwolame twolame.h twolame_init -ltwolame &&
                               { check_lib twolame.h twolame_encode_buffer_float32_interleaved -ltwolame ||
                                 die "ERROR: libtwolame must be installed and version must be >= 0.3.10"; }
-@@ -4464,7 +4466,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
+@@ -4467,7 +4467,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
  enabled libvidstab        && require_pkg_config "vidstab >= 0.98" vid.stab/libvidstab.h vsMotionDetectInit
  enabled libvo_aacenc      && require libvo_aacenc vo-aacenc/voAAC.h voGetAACEncAPI -lvo-aacenc
  enabled libvo_amrwbenc    && require libvo_amrwbenc vo-amrwbenc/enc_if.h E_IF_init -lvo-amrwbenc
@@ -77,7 +79,7 @@ index 7b4cfc5..c98ed75 100755
  enabled libvpx            && {
      enabled libvpx_vp8_decoder && { check_lib2 "vpx/vpx_decoder.h vpx/vp8dx.h" vpx_codec_dec_init_ver -lvpx ||
                                      die "ERROR: libvpx decoder version must be >=0.9.1"; }
-@@ -4494,10 +4496,7 @@ enabled opencl            && { check_lib2 OpenCL/cl.h clEnqueueNDRangeKernel -Wl
+@@ -4497,10 +4497,7 @@ enabled opencl            && { check_lib2 OpenCL/cl.h clEnqueueNDRangeKernel -Wl
                               { check_cpp_condition "OpenCL/cl.h" "defined(CL_VERSION_1_2)" ||
                                 check_cpp_condition "CL/cl.h" "defined(CL_VERSION_1_2)" ||
                                 die "ERROR: opencl must be installed and version must be 1.2 or compatible"; }
