ffmpeg: update pkg-config patch

diff --git a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
--- a/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
+++ b/packages/ffmpeg-0001-Fix-pkg-config-for-static-builds-and-use-it-for-more.patch
@@ -1,6 +1,6 @@
-From f0227e6b3d9c282dbdec3206ce6bddd1dcc5c19c Mon Sep 17 00:00:00 2001
+From 664dca0b87eb68f305978c1c0c25704fc91af157 Mon Sep 17 00:00:00 2001
 From: Martin Herkt <lachs0r@srsfckn.biz>
-Date: Sat, 7 Sep 2013 19:52:05 +0200
+Date: Mon, 23 Sep 2013 13:56:46 +0200
 Subject: [PATCH] Fix pkg-config for static builds and use it for more external
  libs
 
@@ -9,10 +9,10 @@ Subject: [PATCH] Fix pkg-config for static builds and use it for more external
  1 file changed, 12 insertions(+), 13 deletions(-)
 
 diff --git a/configure b/configure
-index 4ff97b4..815fbae 100755
+index f25f7dc..9b0fed0 100755
 --- a/configure
 +++ b/configure
-@@ -2628,6 +2628,8 @@ set_default host_cc
+@@ -2635,6 +2635,8 @@ set_default host_cc
  if ! $pkg_config --version >/dev/null 2>&1; then
      warn "$pkg_config not found, library detection may fail."
      pkg_config=false
@@ -21,7 +21,7 @@ index 4ff97b4..815fbae 100755
  fi
  
  exesuf() {
-@@ -4190,26 +4192,26 @@ enabled gnutls            && require_pkg_config gnutls gnutls/gnutls.h gnutls_gl
+@@ -4217,26 +4219,26 @@ enabled ladspa            && { check_header ladspa.h || die "ERROR: ladspa.h hea
  enabled libiec61883       && require libiec61883 libiec61883/iec61883.h iec61883_cmp_connect -lraw1394 -lavc1394 -lrom1394 -liec61883
  enabled libaacplus        && require "libaacplus >= 2.0.0" aacplus.h aacplusEncOpen -laacplus
  enabled libass            && require_pkg_config libass ass/ass.h ass_library_init
@@ -54,10 +54,10 @@ index 4ff97b4..815fbae 100755
  enabled libopencv         && require_pkg_config opencv opencv/cxcore.h cvCreateImageHeader
  enabled libopenjpeg       && { check_lib openjpeg-1.5/openjpeg.h opj_version -lopenjpeg ||
                                 check_lib openjpeg.h opj_version -lopenjpeg ||
-@@ -4221,11 +4223,11 @@ enabled librtmp           && require_pkg_config librtmp librtmp/rtmp.h RTMP_Sock
- enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/schro.h schro_init
+@@ -4249,11 +4251,11 @@ enabled libschroedinger   && require_pkg_config schroedinger-1.0 schroedinger/sc
  enabled libshine          && require_pkg_config shine shine/layer3.h shine_encode_buffer
  enabled libsoxr           && require libsoxr soxr.h soxr_create -lsoxr
+ enabled libssh            && require_pkg_config libssh libssh/sftp.h sftp_init
 -enabled libspeex          && require libspeex speex/speex.h speex_decoder_init -lspeex
 +enabled libspeex          && require_pkg_config speex speex/speex.h speex_decoder_init
  enabled libstagefright_h264 && require_cpp libstagefright_h264 "binder/ProcessState.h media/stagefright/MetaData.h
@@ -68,7 +68,7 @@ index 4ff97b4..815fbae 100755
  enabled libtwolame        && require libtwolame twolame.h twolame_init -ltwolame &&
                               { check_lib twolame.h twolame_encode_buffer_float32_interleaved -ltwolame ||
                                 die "ERROR: libtwolame must be installed and version must be >= 0.3.10"; }
-@@ -4234,7 +4236,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
+@@ -4262,7 +4264,7 @@ enabled libv4l2           && require_pkg_config libv4l2 libv4l2.h v4l2_ioctl
  enabled libvidstab        && require_pkg_config vidstab vid.stab/libvidstab.h vsMotionDetectInit
  enabled libvo_aacenc      && require libvo_aacenc vo-aacenc/voAAC.h voGetAACEncAPI -lvo-aacenc
  enabled libvo_amrwbenc    && require libvo_amrwbenc vo-amrwbenc/enc_if.h E_IF_init -lvo-amrwbenc
@@ -77,7 +77,7 @@ index 4ff97b4..815fbae 100755
  enabled libvpx            && {
      enabled libvpx_vp8_decoder && { check_lib2 "vpx/vpx_decoder.h vpx/vp8dx.h" vpx_codec_dec_init_ver -lvpx ||
                                      die "ERROR: libvpx decoder version must be >=0.9.1"; }
-@@ -4263,10 +4265,7 @@ enabled opencl            && { check_lib2 OpenCL/cl.h clEnqueueNDRangeKernel -Wl
+@@ -4291,10 +4293,7 @@ enabled opencl            && { check_lib2 OpenCL/cl.h clEnqueueNDRangeKernel -Wl
                               { check_cpp_condition "OpenCL/cl.h" "defined(CL_VERSION_1_2)" ||
                                 check_cpp_condition "CL/cl.h" "defined(CL_VERSION_1_2)" ||
                                 die "ERROR: opencl must be installed and version must be 1.2 or compatible"; }
@@ -90,5 +90,5 @@ index 4ff97b4..815fbae 100755
  if enabled gnutls; then
      { check_lib nettle/bignum.h nettle_mpz_get_str_256 -lnettle -lhogweed -lgmp && enable nettle; } ||
 -- 
-1.8.3.4
+1.8.0.1
 
